/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const HelpMessage = IDL.Record({
  'id' : IDL.Nat,
  'adminReply' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'senderPrincipal' : IDL.Text,
  'repliedAt' : IDL.Opt(Time),
  'message' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'supplier' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'sellingPrice' : IDL.Float64,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'category' : IDL.Text,
  'imageId' : IDL.Opt(ExternalBlob),
  'price' : IDL.Float64,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'adminReply' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'repliedAt' : IDL.Opt(Time),
  'message' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'itemId' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'customerAddress' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'createdAt' : Time,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteHelpMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'getAllHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
  'getMyHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getReviewsByItem' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageRead' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'recordVisit' : IDL.Func([], [], []),
  'replyToHelpMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'replyToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitHelpMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitReview' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const HelpMessage = IDL.Record({
    'id' : IDL.Nat,
    'adminReply' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'senderPrincipal' : IDL.Text,
    'repliedAt' : IDL.Opt(Time),
    'message' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'supplier' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'sellingPrice' : IDL.Float64,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'category' : IDL.Text,
    'imageId' : IDL.Opt(ExternalBlob),
    'price' : IDL.Float64,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'adminReply' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'repliedAt' : IDL.Opt(Time),
    'message' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'itemId' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'customerAddress' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'createdAt' : Time,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteHelpMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'getAllHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [InventoryItem], ['query']),
    'getMyHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getReviewsByItem' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageRead' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'recordVisit' : IDL.Func([], [], []),
    'replyToHelpMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'replyToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitHelpMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };